### ISSUE TITLE
still getting error

### ISSUE THREAD

**Issue by adehghanzadeh** [supaflare/supaflare#27]
Hi again

I still get this error  
 

![image](https://user-images.githubusercontent.com/86428901/190660497-c6d014a4-eee3-4b35-9244-b5f72e4bc01a.png)

I followed the instruction step-by-step

---

your service also has this problem

![](https://user-images.githubusercontent.com/86428901/190661901-4502cd2c-86fa-437c-bd9f-0f33c7d37d2b.png)

its more complicated now

**Comment by rtb1337** [comment]
Sorry if this is not the correct way to communicate this, but I have this exact issue still using the newest version that I forked of your repo. 
When creating a new link I get "Error creating link..." however it appears on the Mange Links section, but I cant visit the link instead I get "Page not found."
I tried with my cloudflare pages domain and my own custom domain that I set in the supaflare cloudflare pages project.
I also looked at the logs on supabase, but haven't really found anything that could tell me what went wrong exactly.

**Comment by alerezaaa** [comment]
@rtb1337 I have updated node (check the pull request), check if its work for you 😉

**Comment by rtb1337** [comment]
@alerezaaa I have tried this yesterday and I also had to update checkout from v2 to v3 (https://github.com/supaflare/supaflare/commit/30364fbf0479e1e394c735a1dd3806d0664c8aa8) in order to get rid of the error message I got before. 
However while that error is gone now I get this error shown in Wrangler CLI:

> ✘ [ERROR] A request to the Cloudflare API (/accounts/***/workers/scripts/supaflare-worker) failed.
> 
>   workers.api.error.unauthorized [code: 10023]
>   
>   If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose

Im certain I have provided the correct data since I followed the steps, but I will check my files and report back if im able to fix it.

**Comment by alerezaaa** [comment]
Okay, thanks for your report

I think I have to leave it to original author, AFA i remember, I redeployed my service about a month ago without error, If I can find anything which can help you, I inform you but hope you figure it out before me 🙂

good luck

**Comment by sainnhe** [comment]
> @alerezaaa I have tried this yesterday and I also had to update checkout from v2 to v3 ([30364fb](https://github.com/supaflare/supaflare/commit/30364fbf0479e1e394c735a1dd3806d0664c8aa8)) in order to get rid of the error message I got before. However while that error is gone now I get this error shown in Wrangler CLI:
> 
> > ✘ [ERROR] A request to the Cloudflare API (/accounts/***/workers/scripts/supaflare-worker) failed.
> > workers.api.error.unauthorized [code: 10023]
> > If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
> 
> Im certain I have provided the correct data since I followed the steps, but I will check my files and report back if im able to fix it.
> 
> Edit: I found this: [cloudflare/workers-sdk#2991](https://github.com/cloudflare/workers-sdk/issues/2991) it shows that using the CLOUDFLARE_API_TOKEN in that case didnt work, while using OAuth did. However I have no clue how to use Oauth for Cloudflare inside Github actions and searching the internet didn't help me either. If anyone has a idea how to make this project work again, feel free to tell me.

I also get 10023 error code when running github workflow. I managed to solve this problem by recreating a new API token, but instead of creating custom token, I used "API token templates" -> "Edit Cloudflare Workers".

**Comment by rtb1337** [comment]
Thank you. I managed to run Github Workflow properly without errors after using the API token template you mentioned instead, however the shortened URLs wont work at all sadly. It states that they are created successfully however when visiting the slug it still shows only the error page of Supaflare.
